version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
    ports:
      - "5432:5432"
    restart: always
    networks:
      - inner-net
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: galactusclb/check-ministry-api:latest
    container_name: api
    ports:
      - "4000:4000"
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@db:5432/test-db
    depends_on:
      - db
    networks:
      - inner-net
    restart: always

  web:
    image: galactusclb/check-ministry-web:latest
    container_name: web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api
    networks:
      - inner-net
    restart: always

networks:
  inner-net:

volumes:
  db_data: