services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - cleaoo-net
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    image: galactusclb/check-ministry-api:latest
    container_name: api
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
      - cleaoo-net
    restart: always

  web:
    image: galactusclb/check-ministry-web:latest
    container_name: web
    ports:
      - "3005:3005"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://api.cs.cleaoo.com/api
    networks:
      - cleaoo-net
    restart: always

networks:
  cleaoo-net:
    external: true

volumes:
  db_data: