FROM node:lts-alpine3.23

RUN npm i -g pnpm

WORKDIR /app

ENV NODE_ENV development
ENV HOSTNAME 0.0.0.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml tsconfig.json ./

RUN pnpm i

COPY . .

EXPOSE 3000

CMD [ "pnpm", "run", "dev" ]